# Generated by Django 3.1.6 on 2021-02-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210219_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='duration',
        ),
        migrations.AlterField(
            model_name='chore',
            name='chore_type',
            field=models.CharField(choices=[('MD', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THUR', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday'), ('ANY', 'Anyday')], default='ANY', max_length=4),
        ),
    ]
