# Generated by Django 3.1.7 on 2021-02-19 16:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210219_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='chore_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MD', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THUR', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday'), ('ANY', 'Anyday')], default='ANY', max_length=4),
        ),
    ]
