# Generated by Django 3.1.7 on 2021-02-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210219_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
