# Generated by Django 3.1.7 on 2021-02-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_record_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='captain',
            field=models.BooleanField(default=False),
        ),
    ]
