# Generated by Django 3.1.7 on 2021-02-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_captain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='captain',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Captain'), (2, 'Member')], default=1),
            preserve_default=False,
        ),
    ]
