# Generated by Django 3.1.7 on 2021-02-19 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_captain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captain',
            name='captain',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
