# Generated by Django 3.1.7 on 2021-02-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210219_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captain',
            old_name='captain',
            new_name='user',
        ),
    ]
