# Generated by Django 3.1.7 on 2021-02-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210219_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captain',
            name='user',
        ),
        migrations.AddField(
            model_name='captain',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='user'),
            preserve_default=False,
        ),
    ]
