# Generated by Django 3.1.7 on 2021-02-19 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210219_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captain',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
