# Generated by Django 3.1.7 on 2021-02-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210219_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Captain',
        ),
    ]
