# Generated by Django 3.1.7 on 2021-02-20 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_captain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chores', to=settings.AUTH_USER_MODEL),
        ),
    ]
