# Generated by Django 3.1.7 on 2021-02-23 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210222_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date-of-record')),
                ('comment', models.TextField(max_length=1000)),
                ('complete', models.BooleanField(default=False)),
                ('assignment_type', multiselectfield.db.fields.MultiSelectField(choices=[('MD', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THUR', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday'), ('ANY', 'Anyday')], default='ANY', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='chore',
            name='chore_type',
        ),
        migrations.RemoveField(
            model_name='chore',
            name='user',
        ),
        migrations.AddField(
            model_name='chore',
            name='points',
            field=models.PositiveIntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='assignment',
            name='chore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chore'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
