# Generated by Django 3.1.7 on 2021-02-24 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_assignment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='core.team'),
            preserve_default=False,
        ),
    ]
