# Generated by Django 3.1.7 on 2021-02-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_assignment_assignment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='comment',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('ANYDAY', 'Anyday')], default='ANY', max_length=10),
        ),
    ]
