# Generated by Django 3.1.7 on 2021-02-27 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_assignment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('ANYDAY', 'Anyday')], default='ANYDAY', max_length=10),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='chore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='core.chore'),
        ),
        migrations.AlterField(
            model_name='pod',
            name='teams',
            field=models.ManyToManyField(related_name='pods', to='core.Team'),
        ),
    ]
