# Generated by Django 3.1.7 on 2021-02-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_feed_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='notification',
        ),
        migrations.AddField(
            model_name='feed',
            name='notification',
            field=models.ManyToManyField(to='core.Notification'),
        ),
    ]
