# Generated by Django 3.1.7 on 2021-02-28 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210228_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='core.team'),
            preserve_default=False,
        ),
    ]
