# Generated by Django 3.1.7 on 2021-03-01 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210228_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='team',
        ),
        migrations.AddField(
            model_name='feed',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.feed'),
            preserve_default=False,
        ),
    ]
