# Generated by Django 3.1.7 on 2021-03-02 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210301_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='name',
        ),
        migrations.AddField(
            model_name='feed',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.team'),
            preserve_default=False,
        ),
    ]
