# Generated by Django 3.1.7 on 2021-03-02 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20210302_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='team',
        ),
        migrations.RemoveField(
            model_name='pod',
            name='pod',
        ),
        migrations.AddField(
            model_name='feed',
            name='pod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pod'),
        ),
        migrations.AddField(
            model_name='pod',
            name='teams',
            field=models.ManyToManyField(related_name='pods', to='core.Team'),
        ),
    ]
