# Generated by Django 3.1.7 on 2021-03-03 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20210303_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='pod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='core.pod'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='core.team'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to=settings.AUTH_USER_MODEL),
        ),
    ]
