# Generated by Django 3.1.7 on 2021-03-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_notification_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='published',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
